### ISSUE TITLE
Disrupt Integration

### ISSUE THREAD

**Issue by ashtif** [JoshuaMKW/Super-Mario-Eclipse#14]
Hi there!

I'm not sure if anybody is still keeping on eye on this repository, but I've come looking for something very specific.

I'm unable to find a memory map online for SMS, and my project requires a memory map to put it simply.

If there's anybody here with a .dmw file, or another sort of ram map for this game, that'd be terrific!

Thanks. Otherwise, if there's nothing you can do to help me, I totally understand, and please go ahead and close this issue! Thanks!

**Comment by JoshuaMKW** [comment]
Hello, sorry for the super late reply, do you still need help?

**Comment by ashtif** [comment]
Forgot to close this issue, but I did end up finding a watchfile. Thanks anyways though!
