### ISSUE TITLE
Game runs very slow at 60fps on Nintendont

### ISSUE THREAD

**Issue by genestrashcan** [JoshuaMKW/Super-Mario-Eclipse#31]
The final Game runs very slow at 60fps on Nintendont even with the first hot patch that fixed the corona mountain softlock

**Comment by JoshuaMKW** [comment]
This is known and won't be fixed. This is an issue due to Sunshine being a poorly optimized game, and until a decompilation for Sunshine is finished, there is now easy way for me to remedy the problem. 60fps is effectively an emulator only experience.
